waitNotificationMs: 500
schedules:
  notifyOfBookingUpdates:
    # every minute
    - '0 */1 * * * *'
  synchronizeBookings:
    # every 10 minutes
    - '0 0/10 * * * *'
  generateDashboard:
    # at 8:10
    - '0 10 8 * * *'
    # at 20:10
    - '0 10 20 * * *'
