const COMMAND_FIND_CLIENT = ['cl', 'c', 'client'];
const COMMAND_BOOKINGS_ARRIVE_ON = 'arrive';
const COMMAND_BOOKINGS_ADDED_AFTER = 'added';
const COMMAND_BOOKING_BY_ID = 'id';
const COMMAND_CLIENT_BY_ID = 'cl_id';
const COMMAND_SYNC = 'sync';
const COMMAND_CREATE = 'create';
const COMMAND_NOT_PREPAID = ['not_payed', 'prepay', 'prepayment', 'pp', 'npp'];
const COMMAND_PREPAID_EXPIRED = ['pp_expired', 'expired'];
const COMMAND_MOVE = 'mv';
const COMMAND_MOVE_IN_BATCH = 'mv_batch';

export {
  COMMAND_FIND_CLIENT,
  COMMAND_BOOKINGS_ARRIVE_ON,
  COMMAND_BOOKINGS_ADDED_AFTER,
  COMMAND_BOOKING_BY_ID,
  COMMAND_CLIENT_BY_ID,
  COMMAND_SYNC,
  COMMAND_CREATE,
  COMMAND_NOT_PREPAID,
  COMMAND_PREPAID_EXPIRED,
  COMMAND_MOVE,
  COMMAND_MOVE_IN_BATCH
};
